import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Applayout from "../components/AppLayout";
import { colors } from "../styles/theme";
import Button from "../components/Button";
import GitHub from "../components/Icons/github";
import { loginWithGithub } from "../firebase/client";
import { useState } from "react";

export default function Home() {
  const [user, setUser] = useState({});

  const handleClick = () => {
    loginWithGithub()
      .then((user) => {
        const { avatar, email } = user;
        setUser(user);
        console.log(user);
      })
      .catch((err) => {
        console.log(err);
      });
  };

  return (
    <>
      <Head>
        <title>Twitter clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Applayout>
        <section>
          <img src="/logo.png" alt="" />
          <h1>Devter</h1>
          <h2>
            Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Consequatur, provident.
          </h2>
          <div>
            <Button onClick={handleClick}>
              <GitHub fill="#fff" />
              Login with Github
            </Button>
          </div>
        </section>
      </Applayout>
      <style jsx>{`
        section {
          display: grid;
          height: 100%;
          place-content: center;
          place-items: center;
        }
        img {
          width: 120px;
        }
        h1 {
          color: ${colors.primary};
          font-weight: 800;
          margin-bottom: 16px;
        }
        h2 {
          font-size: 21px;
          color: ${colors.secondary};
          margin: 0;
          text-align: center;
        }
        div {
          margin-top: 15px;
        }
      `}</style>
    </>
  );
}
